package residuosquimicos

enum LaboratorioList {

    /* CB */
    // Departamento de Antibioticos
    LABORATORIO_DE_FARMACOLOGIA_E_CANCEROLOGIA_EXPERIMENTAIS("Lab. de Farmacologia e Cancerologia Experimentais (Toxologia e Cancerologia Experimental)"),
    LABORATORIO_DE_CULTURA_DE_CELULAS_DEPARTAMENTO_DE_ANTIBIOTICOS("Lab. de Cultura de Celulas"),
    BIOFARMATOX_SALA_1("Laboratorio de Prospeccao Farmacotoxicologica de Produtos Bioativos - BIOFARMATOX - sala 1"),
    BIOFARMATOX_SALA_2("Laboratorio de Prospeccao Farmacotoxicologica de Produtos Bioativos - BIOFARMATOX - sala 2"),
    LAMAI("Laboratorio de Microbiologial Industrial e Ambiental - LAMAI"),
    LEA("Laboratorio de Etnofarmacologia Aplicada - LEA"),
    LABORATORIO_DE_BIOPROCESSOS_E_BIOPRODUTOS("Laboratorio de Bioprocessos e Bioprodutos"),
    LABORATORIO_DE_AULAS_PRATICAS("Laboratorio de Aulas Praticas"),
    LABORATORIO_DE_MEIO_DE_CULTURA("Laboratorio de Meio de Cultura"),
    LABORATORIO_DE_MICROBIOLOGIA_APLICADA_E_ENSAIOS_ANTIMICROBIANOS("Laboratorio de Microbiologia Aplicada e Ensaios Antimicrobianos"),
    LABORATORIO_DE_GENETICA_DE_MICRORGANISMOS("Laboratorio de Genetica de microrganismos"),
    COLECAO_DE_MICROORGANISMOS_UFPEDA("Colecao de Microorganimos - UFPEDA"),
    LABORATORIO_DE_PROCESSOS_BIOTECNOLOGICOS_DA("Laboratorio de Processos Biotecnologicos"),
    LABORATORIO_DE_FISIOLOGIA_DE_BIOQUIMICA_DE_MICRORGANISMO("Laboratorio de Fisiologia e Bioquimica de Microrganismo"),
    LQIT("Laboratorio de Quimica e Inovacao Terapeutica - LQIT"),
    LABORATORIO_DE_QUIMICA_DE_PRODUTOS_NATURAIS_DA("Laboratorio de Quimica de Produtos Naturais"),
    LABORATORIO_DE_SINTESE_E_QUIMICA_DE_PRODUTOS_NATURAIS("Laboratorio de Sintese e Quimica de Produtos Naturais"),
    LABORATORIO_DE_SINTESE_DE_SUBSTANCIAS_DE_INTERESSE_TERAPEUTICO("Lab.  de Sintese de Substâncias de Interesse Terapeutico"),
    LABORATORIO_DE_PRODUTOS_NATURAIS_E_SINTETICOS("Laboratorio de Produtos Naturais e sinteticos"),

    // Departamento de Anatomia Humana
    LABORATORIO_DE_ANATOMIA_E("Laboratorio de Anatomia E"),
    SALA_DE_DISSECACAO_2("Sala de Dissecacao 2"),
    LABORATORIO_DE_ANATOMIA_D("Laboratorio de Anatomia D"),
    LABORATORIO_DE_ANATOMIA_A("Laboratorio de Anatomia A"),
    LABORATORIO_DE_ANATOMIA_B("Laboratorio de Anatomia B"),
    LABORATORIO_DE_ANATOMIA_C("Laboratorio de Anatomia C"),
    LABORATORIO_DE_DISSECACAO_1("Sala de Dissecacao 1"),
    LABORATORIO_DE_HISTOQUIMICA("Laboratorio de Histoquimica"),
    LABORATORIO_DE_PERFUSAO("Laboratorio de Perfusão"),
    LABORATORIO_DE_EXTEROTAXIA("Laboratorio de Exterotaxia"),
    BIOTERIO_ANATOMIA("Bioterio"),

    // Departamento de Biofísica  Radiologia
    LABORATORIO_DE_RADIOLOGIA("Laboratorio de Radiobiologia"),
    LABORATORIO_DE_BIOFISICA_QUIMICA("Laboratorio de Biofisica Quimica"),
    LBCM("Laboratorio de Biofisica Celular Molecular- LBCM"),
    BIOFISICA_DAS_MEMBRANAS_E_CELULAS_DR_OLEG_KRASILNIKOV("Biofisica das Membranas e Celulas Tronco- Dr.Oleg Krasilnikov"),
    ENEGNHARIA_BIOMEDICA("Engenharia Biomedica"),

    // Departamento de Bioquímica
    LABORATORIO_DE_BIOTECNOLOGIA_BIOQUIMICA("Laboratorio de Biotecnologia"),
    BIOTERIO_BIOQUIMICA("Bioterio"),
    LABORATORIO_DE_ENZIMOLOGIA("Laboratorio de Enzimologia"),
    BIOPROT_1("Laboratorio de Bioquimica de proteinas (BIOPROT 1)"),
    BIOPROT_2("Laboratorio de Bioquimica de proteinas (BIOPROT 2)"),
    LAB_DE_LIPIDIOS_METABOLISTMO_DE_LIPITIODS_E_LIPOPROTEINAS("Lab.  de Lipidios, Metabolismo de Lipidios e Lipoproteinas"),
    LABORATORIO_DE_QUIMICA_DE_PRODUTOS_NATURAIS("Laboratorio de Quimica de Produtos Naturais"),
    LABORATORIO_DE_ENGENHARIA_METABOLICA("Laboratorio de Engenharia Metabolica"),
    BIONANO("Laboratorio de Bionanotecnologia (BIONANO)"),
    LABORATORIO_DE_BIOLOGIA_MOLECULAR_DB("Laboratorio de Biologia Molecular"),
    SALAS_DE_AULAS_PRATICAS_BIOFISICA("Salas de Aulas Praticas - Biofisica"),
    SALAS_DE_AULAS_PRATICAS_BIOQUIMICA("Salas de Aulas Praticas - Bioquimica"),

    // Departamento de Botânica
    LEVA("Laboratorio de Ecologia Vegetal Aplicada (LEVA)"),
    LEAF("Laboratorio de Ecologia Aplicada e Fitoquimica (LEAF)"),
    LABORATORIO_DE_INTERACOES_MULTITROFICAS("Laboratorio de Interações Multitroficas"),
    LIPA("Laboratorio de Interacao Planta-Animal (LIPA)"),
    LABORATORIO_DIDATICO_DE_MORFOLOGIA_E_FISIOLOGIA_VEGETAL("Laboratorio Didatico de Morfologia e Fisiologia Vegetal"),
    LABORATORIO_DE_ECOFISIOLOGIA_VEGETAL("Laboratorio de Ecofisiologia Vegetal"),
    LABORATORIO_DE_SISTEMATICA_DE_FANEROGAMOS("Laboratorio Sistematica de Fanerogamos"),
    POLINIZAR("Laboratorio de Biologia Floral e reprodutiva- POLINIZAR"),
    LABORATORIO_DE_MORFOTAXONOMIA_VEGETAL("Laboratorio de Morfotaxonomia Vegetal"),
    LABORATORIO_DE_CITOGENETICA_E_EVOLUCAO_VEGETAL("Laboratorio de Citogenetica e Evolucao Vegetal"),
    LABORATORIO_DE_BIOLOGIA_DE_BRIOFITAS("Laboratorio de Biologia de Briofitas"),
    LABORATORIO_DE_ECOLOGIA_APLICADA("Laboratorio de Ecologia Aplicada"),
    LABORATORIO_DE_PTERIDOFITAS("Laboratorio de Pteridofitas"),
    LABORATORIO_DE_MIXOMICETOS("Laboratorio de Mixomicetos"),
    LABORATORIO_DE_ANATOMIA_VEGETAL("Laboratorio de Anatomia Vegetal"),

    // Departamento de Fisiologia e Farmacologia
    LABORATORIO_DE_REATIVIDADE_VASCULAR("Laboratorio de Reatividade Vascular"),
    LABORATORIO_DE_NEUROFISIOLOGIA_1("Laboratorio de Neurofisiologia 1"),
    BIOTERIO_FISIOLOGIA_I("Bioterio I"),
    BIOTERIO_FISIOLOGIA_II("Bioterio II"),
    LABORATORIO_DE_FISIOLOGIA_CARDIOPULMONAR("Laboratorio  de Fisiologia Cardiopulmonar"),
    LABORATORIO_DE_ENDOCRINOLOGIA_E_METABOLISMO("Laboratorio de Endocrinologia e Metabolismo"),
    LABORATORIO_DE_PANCREAS_ENDOCRINO("Laboratorio de Pâncreas Endocrino"),
    LABORATORIO_DE_FARMACOLOGIA_CARDIOVASCULAR("Laboratorio de Farmacologia Cardiovascular"),
    LABORATORIO_DE_FISIOLOGIA_COMPARADA("Laboratorio de Fisiologia Comparada"),
    LABORATORIO_DE_NEUROENDOCRINOLOGIA_E_METABOLISTMO_1("Laboratorio de Neuroendocrinologia e Metabolismo 1"),
    LABORATORIO_DE_NEUROENDOCRINOLOGIA_E_METABOLISTMO_2("Laboratorio de Neuroendocrinologia e Metabolismo 2"),
    SALA_MEZANINO("Sala Mezanino (aulas)"),
    LABORATORIO_DE_FARMACOLOGIA_RENAL("Laboratorio de Farmacologia Renal"),
    LABORATORIO_DE_FARMACOLOGIA_E_TOXICOLOGIA_PRE_CLINICA("Laboratorio de Farmacologia e Toxicologia Pre-Clinica"),
    LABORATORIO_DE_PRODUTOS_BIOATIVOS("Laboratorio de Produtos Bioativos"),
    LABORATORIO_DE_NEUROFARMACOLOGIA("Laboratorio de Neurofarmacologia"),
    LABORATORIO_DE_NEUROFISIOLOGIA_2("Laboratorio de Neurofisiologia 2"),

    // Departamento de Genetica
    LABORATORIO_DE_GENETICA_E_BIOTECNOLOGIA_VEGETAL("Laboratorio de Genetica e Biotecnologia Vegetal"),
    DINE("Laboratorio de Genoma e Proteônica (DINE)"),
    LABORATORIO_DE_GENETICA_E_CITOGENETICA_ANIMAL_E_HUMANA("Laboratorio de Genetica e Citogenetica Animal e Humana"),
    LABORATORIO_DE_GENETICA_MOLECULAR("Laboratorio de Genetica Molecular"),
    LABORATORIO_DE_GENETICA_MICROORGANISMOS("Laboratorio de Genetica Microorganismos"),
    LED("Laboratorio de Experimentacao em Drosophila ( LED)"),
    LABORATORIO_DE_GENETICA_MOLECULAR_HUMANA("Laboratorio de Genetica Molecular Humana"),
    LABORATORIO_DE_BIO_INFORMATICA_E_BILOGIA_EVOLUTIVA("Laboratorio de Bio-informatica e Biologia Evolutiva"),

    // Departamento de Histologia e Embriologia
    LABORATORIO_DE_CULTURA_DE_CELULAS("Laboratorio de Cultura de Celulas"),

    // Departamento de Micologia
    LABORATORIO_DE_POS_GRADUACAO_EM_BIOLOGIA_DE_FUNGOS_1("Laboratorio de Pos-graduacao em Biologia de Fungos 1"),
    LABORATORIO_DE_POS_GRADUACAO_EM_BIOLOGIA_DE_FUNGOS_2("Laboratorio de Pos-graduacao em Biologia de Fungos 2"),
    LABORATORIO_DE_MICOLOGIA_MEDICA_HUMANA_E_VETERINARIA("Laboratorio de Micologia Medica humana e Veterinaria"),
    LABORATORIO_DE_BIOLOGIA_MOLECULAR_DE_FUNGOS("Laboratorio  de Biologia Molecular de Fungos"),
    PGBP_2("Laboratorio de Taxonomia  e Sistematica de Fungos (PGBP 2)"),
    LABORATORIO_DE_CITOLOGIA_E_GENETICA("Laboratorio de Micologia Ambiental ( Lab. Citologia e Genetica)"),
    LABORATORIO_DE_HIFOMICETOS("Laboratorio de Hifomicetos"),
    LABORATORIO_DE_MICORRIZAS("Laboratorio de Micorrizas"),
    LABORATORIO_DE_TAXONOMIA_BIOTECNOLOGIA("Departamento de Taxonomia Biotecnologia"),
    IMUNODIAGNOSTICO_DE_MICOSES_SISTEMICAS("Imunodiagnostico de Micoses Sistemicas"),
    LABORATORIO_DE_FUNGOS_FITOPATOGENICOS("Laboratorio de Fungos Fitopatogenicos"),
    MICOTECA("Micoteca"),
    MEIO_DE_CULTURA("Meio de Cultura"),
    HERBARIO_MICOLOGIA("Herbario"),

    // Departamento de Zoologia
    LABORATORIO_DE_AQUICULTURA("Laboratorio de Agricultura"),
    ARREAGUA("Laboratorio de Avaliacao, Recuperacao e Restauracao de Ecossistemas – ARREAGUA"),
    LACMAR("Laboratorio de Comunidades Marinhas - LACMAR"),
    LAEBRY("Laboratorio de Estudos de Bryozoa - LAEBRY"),
    LABORATORIO_DE_ETNOECOLOGIA_E_EDUCACAO_AMBIENTAL("Laboratorio de Etnoecologia e Educacao Ambiental"),
    LABORATORIO_DE_ETOLOGIA("Laboratorio de Etologia"),
    LAPTX("Laboratorio de Toxinas e Herpetologia (Animais Peçonhentos e Toxinas - LAPTX)"),
    LABORATORIO_DE_BIOLOGIA_DE_CONSERVACAO("Laboratorio de Biologia de Conservacao"),
    LABORATORIO_DE_BIOLOGIA_DE_CRUSTACEOS("Laboratorio de Biologia de Crustaceos"),
    LABORATORIO_DE_CIENCIAS_APLICADAS_A_CONSERVACAO_DA_BIODIVERSIDADE("Laboratorio de Ciencias Aplicada à Conservacao da Biodiversidade"),
    LACIMME("Laboratorio de Cultivo de Meiofauna Marinha e Estuarina – LACIMME"),
    LABDIN("Laboratorio de Dinâmica de Populações - LABDIN"),
    LABORATORIO_DE_ECOTOXICOLOGIA_AQUATICA("Laboratorio de Ecotoxicologia Aquatica"),
    LABORATORIO_DE_ENTOMOLOGIA_APLICADA("Laboratorio de Entomologia Aplicada (Insetario)"),
    LABORATORIO_DE_ETOMOLOGIA_FORENSE("Laboratorio de Entomologia Forense (Insetos Necrofagos)"),
    LABORATORIO_DE_GENOMICA_EVOLUTIVA_E_AMBIENTAL("Laboratorio de Genômica Evolutiva e Ambiental (Biotecnologia)"),
    LIT("Laboratorio de Invertebrados Terrestres (LIT)"),
    LABORATORIO_DE_MASTOZOOLOGIA("Laboratorio de Mastozoologia"),
    LABORATORIO_DE_MEIOFAUNA("Laboratorio de Meiofauna"),
    LABORATORIO_DE_ORNITOLOGIA("Laboratorio de Ornitologia"),
    LABPOR("Laboratorio de Porifera - LABPOR"),
    LABORATORIO_DE_TAXONOMIA_E_ECOLOGIA_DE_INSETOS("Laboratorio de Taxonomia e Ecologia de Insetos"),
    LABORATORIO_DE_10("Laboratorio 10 (para aulas)"),
    LABORATORIO_DE_07("Laboratorio 07 (para aulas)"),

    // Laboratorio Central
    HERBARIO_LABORATORIO_CENTRAL("Herbario"),
    LABORATORIO_DE_GENOMICA_E_EXPRESSAO_GENICA("Laboratorio de Genômica e expressão Genica"),
    SALA_DE_COLETAS_GINECOLOGICAS("Sala de Coletas Ginecologicas"),
    LABORATORIO_DE_COLETAS_SANGUE("Laboratorio de Coletas (Sangue)"),
    LEMTE("Laboratorio de Estudos Moleculares e Terapia Experimental (LEMTE)"),
    LABORATORIO_DE_HEMATOLOGIA_LABORATORIO_CENTRAL("Laboratorio de Hematologia"),
    LABORATORIO_DE_BIOTECNOLOGIA_LC("Laboratorio de Biotecnologia"),
    LABORATORIO_DE_BIOTECNOLOGIA_ANEXO("Laboratorio de Biotecnologia (Anexo)"),
    LABORATORIO_DE_BIOQUIMICA_CLINICA_PARASITOLOGIA_E_URINALISES("Laboratorio de Bioquimica Clinica (Parasitologia e Urinalises)"),
    LABORATORIO_DE_CULTURA_DE_CELULAS_LABORATORIO_CENTRAL("Laboratorio de Cultura de Celulas"),
    LABORATORIO_MOLECULAR("Laboratorio Molecular"),
    LABORATORIO_DE_CITOLOGIA_CLINICA_CB("Laboratorio de Citologia Clinica"),

    /* CCS */

    // Departamento de Ciencias Farmaceuticas
    NCOMC("Nucleo de Controle de Qualidade de Medicamentos Correlatos (NCQMC)"),
    NUDFAC("Nucleo de Desenvolvimento Farmaceutico e Cosmetico (NUDFAC)"),
    LAPETOX("Laboratorio de Toxicologia (LAPETOX)"),
    UAC("Laboratorio de Analise Clinica (UAC)"),
    LABORATORIO_DE_MICROBIOLOGIA_CLINICA("Laboratorio de Microbiologia Clinica"),
    LABSINFA("Laboratorio de Planejamento Avaliacao e Sintese de Farmacos (LABSINFA)"),
    FARMACOGNOSIA_I_E_II("Farmacognosia I e II"),
    LABORATORIO_DE_FARMACEUTICA("Laboratorio de Quimica Farmaceutica"),
    LAPRONAT("Laboratorio de Produtos Naturais (LAPRONAT)"),
    LABORATORIO_DE_INFORMATICA_DCF("Laboratorio de Informatica"),
    LABORATORIO_DE_PRODUTOS_HOMOTERAPICOS("Laboratorio de Produtos Homoterapicos"),
    LABORATORIO_DE_CITOLOGIA_CLINICA_CCS("Laboratorio de Citologia Clinica"),
    LABORATORIO_DE_COSMETICOS_E_SANIFICANTES("Laboratorio de Cosmeticos e Sanificantes"),
    FARMACIA_ESCOLA("Farmacia Escola"),
    LQTM("Laboratorio de Quimica Teorica Medicinal (LQTM)"),
    LABORATORIO_DE_FARMACOTECNICA_I_II("Laboratorio de Farmacotecnica I e II (NUDFAC)"),
    LABORATORIO_DE_PESQUISA_DCF("Laboratorio de Pesquisa"),
    LABORATORIO_DE_IMUNOLOGIA_CLINICA("Laboratorio de Imunologia Clinica"),
    BIOTERIO_DEPARTAMENTO_DE_CIENCIAS_FARMACEUTICAS("Bioterio"),
    CENTRO_DE_PESQUISA_DESENVOLVIMENTO_E_INOVACAO("Centro de Pesquisa, Desenvolvimento e Inovacao (PD&I) (NUDFAC)"),
    LABORATORIO_DE_ANALISE_MICROBIOLOGICA("Laboratorio de Analise Microbiologica"),
    LPQM("Laboratorio de Planejamento em Quimica Medicinal (LPQM)"),
    LABORATORIO_DE_TECNOLOGIA_DE_MEDICAMENTOS("Laboratorio de Tecnologia  de Medicamentos"),
    LABORATORIO_DE_CONTROLE_MICROBIOLOGICO("Laboratorio de Controle Microbiologico"),
    LABORATORIO_DE_SINTESE_ORGANICA_APLICADA_E_FARMACOS("Laboratorio de Sintese Orgânica Aplicada a Farmacos"),
    LABORATORIO_DE_BIOTECNOLOGIA_E_PRODUCAO_DE_HEMODERIVADOS("Laboratorio de Biotecnologia e Producao de Hemoderivados"),
    LABORATORIO_DE_BIOQUIMICA_CLINICA("Laboratorio de Bioquimica Clinica"),

    // Departamento de Cirurgia
    MODULO_DE_CIRURGIA_ABDOMINAL("Modulo de cirurgia abdominal, introducao a clinica e a tecnica cirurgica"),
    MODULO_DE_CIRURGIA_UROLOGIA_E_VASCULAR("Modulo de cirurgia, urologia e vascular"),
    MODULO_DE_CIRURGIA_TRAUMATOLOGICA("Modulo de cirurgia traumatologica"),
    MODULO_DE_CIRURGIA_TRAUMATOLOGICA_ORTOPEDISTA("Modulo de cirurgia traumatologica/ortopedia"),
    MODULO_DE_CIRURGIA_PEDIATRICA("Modulo de cirurgia pediatrica"),
    MODULO_DE_CIRURGIA_OFTAMOLOGICA("Modulo de cirurgia oftamologica"),
    MODULO_DE_CIRURGIA_OTORRINOLOGICA("Modulo de cirurgia Otorrinologica"),
    MODULO_DE_CIRURGIA_CIRURGIA_VASCULAR("Modulo de cirurgia vascular"),
    NUCLEO_DE_CIRURGIA_EXPERIMENTAL("Nucleo de Cirurgia Experimental"),

    // Departamento  de Clínica Odontologica Preventiva
    CLINICA_CEO("Clinica CEO"),
    ABORATORIO_DE_ORTONDOTIA("Laboratorio de Ortondotia"),
    CLINICA_INTEGRAL("Clinica Integral"),
    CLINICA_DE_ODONTOLOGIA_PREVENTIVA("Clinica de Odontologia Preventiva"),
    ABORATORIO_DE_ESTOMATOLOGIA("Laboratorio de Estomatologia"),
    ABORATORIO_DE_RADIOLOGIA("Laboratorio de Radiologia"),
    PERIONDOTIA("Periodontia"),
    PATOLOGIA_DCOP("Patologia"),

    // Departamento de Enfermagem
    LABORATORIO_DE_ENFERMAGEM("Laboratorio de Enfermagem"),

    // Departamento de Fisioterapia
    LABORATORIO_DE_FISIOTERAPIA_CARDIO_RESPIRATORIO("Laboratorio de Fisioterapia Cardio Respiratorio"),
    LABORATORIO_DE_RECURSOS_TERAPEUTICO_ANUAIS("Laboratorio de Recursos Terapeutico anuais"),
    LABORATORIO_DE_CINESOLOGIA("Laboratorio de Cinesologia"),
    LABORATORIO_DE_ELETROTERMOFOTOTERAPIA("Laboratorio de Eletrotermofototerapia"),

    // Departamento de Fonodiaulogia
    CLINICA_DE_FONODIAULOGICA("Clinica de Fonodiaulogia (3 Laboratorios)"),

    // Departamento de Medicina Tropical
    LABORATORIO_DE_AULAS_PRATICAS_8("Laboratorio  de aulas praticas 8"),
    LABORATORIO_DE_AULAS_PRATICAS_7("Laboratorio  de aulas praticas 7"),
    LABORATORIO_DE_MEIOS_DE_CULTIVO("Laboratorio de Meios de Cultivo"),
    LABORATORIO_DE_ESTERELIZACAO("Laboratorio de Esterelizacao"),
    LABORATORIO_DE_BIOFILMES("Laboratorio de Biofilmes"),
    LABORATORIO_DE_GENETICA_BACTERIANA("Laboratorio de Genetica Bacteriana"),
    LABORATORIO_DE_BACTERIOLOGIA("Laboratorio de Bacteriologia"),
    CORREDOR("Corredor"),
    MOLUSCARIO("Moluscario"),
    LABORATORIO_DE_PROCESSAMENTO_DE_AMOSTRAS("Laboratorio Processamento de amostras"),
    SALA_DE_CULTURA("Sala de Cultura"),
    LABORATORIO_DE_PESQUISAS_DE_OPORTUNISTAS("Laboratorio de Pesquisas de oportunistas"),
    SALA_DE_METODOS("Sala de Metodos"),

    // Departamento de Nutricao
    LNC("Laboratorio de Nutricao Clinica (LNC)"),
    LEAAL("Laboratorio de Experimentacao  e Analise de Alimentos (LEAAL)"),
    LEAAL_FISICO_QUIMICA("LEAAL - Laboratorio de Fisico-Quimica"),
    LEAAL_MICROSCOPIA("LEAAL - Laboratorio de Microscopia"),
    LEAAL_MUTIUSUARIO("LEAAL - Laboratorio Multiusuario"),
    LEAAL_MICROBIOLOGIA_BACTERIAS("LEAAL - Laboratorio de Microbiologia (Bacterias)"),
    LEAAL_MICROBIOLOGIA_FUNGOS("LEAAL - Laboratorio  de Microbiologia (Fungos)"),
    LAB_DE_ESTUDOS_EM_NUTRICAO_E_INSTRUMENTACAO_BIOMEDICA("Lab. de Estudos em Nutricao e Instrumentacao Biomedica"),
    LAB_DE_ESTUDOS_EM_NUTRICAO_E_INSTRUMENTACAO_BIOMEDICA_3_BIOTERIOS("Lab. de Estudos em Nutricao e Instrumentacao Biomedica ( 3 BIOTeRIOS)"),
    LNED("Laboratorio de Nurtricao Experimental e Dietetica (LNED)"),
    LNED_BIOTERIO("Laboratorio de Nurtricao Experimental e Dietetica (LNED) -  BIOTeRIO"),
    BIOTERIO_NUTRICAO("Bioterio ( 3 unidades)"),
    SALA_DE_SACRIFICIOS_NUTRICAO("Sala de Sacrificios"),
    LNSP("Laboratorio de Nutricao em Saude Publica (LNSP)"),
    LBQN_1("Laboratorio de Bioquimica da Nutricao 1 (LBQN)"),
    LBQN_2("Laboratorio de Bioquimica da Nutricao 2 (LBQN)"),
    LAFINNT("Laboratorio de Fisiologia da Nutricao Naide Teodosio (LAFINNT)"),


    // Departamento de Patologia
    LABORATORIO_DE_PATOLOGIA_MOLECULAR("Laboratorio de Patologia Molecular"),
    LABORATORIO_DE_PATOLOGIA_POS("Laboratorio de Patologia (Pos-Graduacao)"),
    MUSEU_PATOLOGIA("Museu"),
    HD_PATOLOGIA("Laboratorio de Patologia (HC)"),
    LIKA_PATOLOGIA("Laboratorio de Patologia (LIKA)"),

    // Departamento de Protese e Cirurgia Bucofacial
    LABORATORIO_DE_DENTISTA_E_MATERIAIS_DENTARIOS("Laboratorios de Dentista e Materiais Dentarios"),
    BLOCO_CIRURGICO("Bloco Cirurgico"),
    CLINICA_INTEGRADA_E_CIRURGICA("Clinica Integrada e Cirurgica"),
    LABORATORIO_DE_DENTISTA_2_3_ENDODONTIA("Laboratorio de Dentista 2 e 3 e Endodontia"),
    NAPA("Nucleo de Pronto Atendimento (NAPA)"),
    CLINICA_DE_PROTESES("Clinica de Proteses"),
    AMBULATORIO_DE_TRAUMATOLOGIA("Ambulatorio de Traumatologia (Lab. de Cirurgia e Traumatologia Buco-Maxilo-Facial)"),

    /* CTG */
    // Departamento de Engenharia Cartografica
    LAGEO("Laboratorio de Astronomia e Geodesia (LAGEO)"),
    LACAD("Laboratorio de Cadastro e Gestão Territorial (LACAD)"),
    LACCOST("Laboratorio de Cartografia Costeira (LACCOST)"),
    LAFOTO("Laboratorio de Fotogrametria (LAFOTO)"),
    LAINFO("Laboratorio de Informatica (LAINFO)"),
    LAMEPE("Laboratorio de Metrologia e Posicionamento Espacial (LAMEPE)"),
    LAPROC("Laboratorio de Processamento de Imagens (LAPROC)"),
    LASENSO("Laboratorio de Sensoriamento Remoto (LASENSO)"),
    LATEGEO("Laboratorio de Tecnologias da Geoinformacao (LATECGEO)"),
    LATOP("Laboratorio de Topografia (LATOP)"),

    // Departamento de Engenharia Civil
    LABORATORIO_DE_HIDRAULICA_APLICADA("Laboratorio de Hidraulica Aplicada"),
    LSA("Laboratorio de Saneamento Ambiental (LSA)"),
    GEOPROCESSAMENTO_E_RECURSOS_HIDRICOS("Geoprocessamento e Recursos Hidricos"),
    HIDROLOGIA("Hidrologia"),
    SOLOS_E_INSTRUMENTACAO("Solos e Instrumentacao"),
    LABORATORIO_DE_COMPUTACAO_DE_ALTO_DESEMPENHO("Laboratorio de Computacao de Alto Desempenho"),
    LABORATORIO_DE_MATERIAIS_E_ESTRUTURAS("Laboratorio de Materiais e Estruturas"),
    LABORATORIO_DE_TRANSPORTES("Laboratorio de Transportes"),

    // Departamento de Engenharia Mecânica
    LABORATORIO_DE_USINAGEM("Laboratorio de Usinagem"),
    LABORATORIO_DE_METALOGRAFIA_E_CARACTERIZACAO_MICROESTRUTURAL("Laboratorio de Metalografia e Caracterizacao Microestrutural"),
    LABORATORIO_DE_FUSAO_E_TRANSFORMACAO_DE_FASE("Laboratorio de Fusão e Transformacao de Fase"),
    LEDEX("Laboratorio de Difracao e Espalhamento de Raios-X - LEDEX"),
    LABORATORIO_DE_ENSAIOS_MECANICOS("Laboratorio de Ensaios Mecânicos"),
    AREA_DE_TESTES_DE_TURBINAS_EOLICAS("area de Testes de Turbinas Eolicas"),
    AREA_DE_TESTES_DE_SISTEMAS_HIBRIDOS_EOLICO_SOLAR_BATERIA("area de Testes de Sistemas Hibridos - Eolico/Solar/Bateria"),
    TURBINA_EOLICA_DE_FERNANDO_DE_NORONHA("Turbina Eolica de Fernando de Noronha"),
    LABTERMO_I("Sistemas e Processos Termicos, (LABTERMO I)"),
    LABTERMO_II("Refrigeracao e Conforto Ambiental, (LABTERMO II)"),
    LABTERMO_III("area de Teste de Motores, (LABTERMO III)"),
    LABTERMO_IV("Simulacao Numerica e Desenvolvimento de Software, (LABTERMO IV)"),
    LES_UFPE("Laboratorio de Energia Solar, (LES/UFPE)"),
    LABCOM("Laboratorio de Computacao para Mecânica Computacional - LABCOM"),
    FADLAB("Laboratorio de Computacao de Alto Desempenho - PADLAB"),
    LABEND("Laboratorio de Ensaios Não-destrutivos - LABEND"),
    LABGESSO("Laboratorio de Tecnologia do Gesso - LABGESSO"),
    LDP_FLU("Laboratorio Didatico-pedagogico de Fluidos - LDP-FLU"),

    // Departamento de Engenharia Química
    LABORATORIO_DE_ANALISE_INSTRUMENTAL("Laboratorio de Analise Instrumental"),
    LABORATORIO_DE_ELETROQUIMICA_CORROSAO("Laboratorio de Eletroquimica/Corrosão"),
    LABORATORIO_DE_ENGENHARIA_QUIMICA("Laboratorio de Engenharia Quimica"),
    LABORATORIO_DE_MICROBIOLOGIA("Laboratorio de Microbiologia"),
    LABORATORIO_DE_ORGANICA("Laboratorio de Orgânica"),
    LABORATORIO_DE_QUIMICA_ANALITICA("Laboratorio de Quimica Analitica"),
    LABORATORIO_DE_QUIMICA_INORGANICA("Laboratorio de Quimica Inorgânica"),
    LABORATORIO_DE_HIALOTCNIA("Laboratorio de Hialotcnia"),
    LABORATORIO_DE_ANALISES_MINERAIS_SOLOS_E_AGUAS("Laboratorio de Analises Minerais Solos e agua"),
    LABORATORIO_DE_COMBUSTIVEL("Laboratorio de Combustivel"),
    LABORATORIO_DE_CONTROLE_DE_QUALIDADE("Laboratorio de Controle de Qualidade"),
    LABORATORIO_DE_CROMATOGRAFIA_INSTRUMENTAL("Laboratorio de Cromatografia Instrumental"),
    LABORATORIO_DE_ENGENHARIA_AMBIENTAL_E_DA_QUALIDADE("Laboratorio de Engenharia Ambiental e da Qualidade"),
    LABORATORIO_DE_MATERIAIS_POLIMERICOS_E_CARACTERIZACAO("Laboratorio de Materiais Polimericos e Caracterizacao"),
    LABORATORIO_DE_MICROBIOLOGIA_AMBIENTAL("Laboratorio de Microbiologia Ambiental"),
    LABORATORIO_DE_MICROBIOLOGIA_INDUSTRIAL("Laboratorio de Microbiologia Industrial"),
    LABORATORIO_DE_PROCESSOS_BIOTECNOLOGICOS_EQ("Laboratorio de Processos Biotecnologicos"),
    LABORATORIO_DE_PROCESSO_CATALITICOS("Laboratorio  de Processo Cataliticos"),
    LABORATORIO_DE_PROCESSOS_E_TECNOLOGIA_AMBIENTAIS("Laboratorio de Processos  e Tecnologia Ambientais"),
    LABORATORIO_DE_PROCESSOS_QUIMICOS("Laboratorio de Processos Quimicos"),
    LABORATORIO_DE_TECNOLOGIAS_LIMPAS("Laboratorio de Tecnologias Limpas"),
    LABORATORIO_DE_CONTROLE_E_OTIMIZACAO_DE_PROCESSOS("Laboratorio  de Controle e Otimizacao de Processos"),

    // Departamento de Engenharia de Producao
    LABORATORIO_DE_PLANEJAMENTO_E_GESTAO_DE_RECURSOS_HIDRICOS("Laboratorio de Planejamento e Gestão de Recursos Hidricos"),
    LABORATORIO_DE_RISCOS_TECNOLOGICOS("Laboratorio de Riscos Tecnologicos"),

    // Departamento de Eletrônicos e Sistemas
    LABORATORIO_DE_ENGENHARIA_BIOMEDICA("Laboratorio de Engenharia Biomedica"),

    // Departamento de Engenharia de Minas
    LABORATORIO_DE_QUIMICA_INTERFACE("Laboratorio de Quimica interface"),
    LABORATORIO_DE_METALURGIA_EXTRATIVA("Laboratorio de Metalurgia Extrativa"),
    LABORATORIO_DE_COMUNICACAO("Laboratorio de Comunuicao"),
    LAPLA("Laboratorio de Planejamento de Lavra - LAPLA"),
    LABORATORIO_DE_CONTROLE_AMBIENTAL_DE_MINERACAO("Laboratorio de Controle Ambiental de Mineracao"),
    LAB_DE_ENSINO_E_PESQUISA_EM_AUTOMACAO_NA_MINERACAO("Lab.  de Ensino e Pesquisa em Automocao na Mineracao"),

    // Departamento de Energia Nuclear
    LABORATORIO_DE_MICROBIOLOGIA_DE_SOLO("Laboratorio de Microbiologia de Solo"),
    LABORATORIO_DE_FERTILIDADE_DE_SOLOS("Laboratorio de Fertilidade de Solos"),
    LABORATORIO_DE_FISICA_DE_SOLOS("Laboratorio de Fisica de Solos"),
    LABORATORIO_DE_PROTECAO_RADIOLOGICA("Laboratorio de Protecao Radiologica"),
    LABORATORIO_DE_DOSIMETRIA_AMBIENTAL("Laboratorio de Dosimetria Ambiental"),
    LAMBDA("Laboratorio de Modelagem e Bisiometria Aplicada (LAMBDA)"),
    LABORATORIO_DE_METROLOGIA_DAS_RADIACOES_LONIZONTES("Laboratorio de Metrologia das Radiações Lonizontes"),
    LABORATORIO_DE_RADIOQUIMICA("Laboratorio de Radioquimica"),


    // Departamento de Oceanografia
    LOQUIM("Laboratorio de Oceanografia Quimica (LOQUIM)"),
    LABORATORIO_DE_FITOPLANCTON("Laboratorio de Fitoplâncton"),
    LABORATORIO_DE_ZOOPLANCTION("Laboratorio de Zooplâncton"),
    LABORATORIO_DE_BENTOS_I("Laboratorio de Bentos"),
    LABORATORIO_DE_BENTOS_II("Laboratorio de Bentos II"),
    LABORATORIO_DE_NECTON("Laboratorio de Necton"),
    LOFEC("Lab. de Fisica Marinha  Fisica Esturiana e Costeira (LOFEC)"),
    LABORATORIO_DE_OCEONAGRAFIA_GEOLOGICA("Laboratorio de Oceanografia Geologica"),
    ORGANOMAR("Lab. Composto de Orgânicos em Ecossistema Costeiros e Marinhos (OrganoMAR)"),
    LABOGEO("Laboratorio de Carcinologia  (LABOGEO)"),
    LACE("Laboratorio de Cultivo e Ecotoxocologia (LACE)"),
    LEGECE("Lab. de Ecologia e Gerenciamento de Ecossistemas Costeiros e Estuarino (LEGECE)"),
    LABORATORIO_DE_HIDRODINAMICA_COSTEIRA("Laboratorio de Hidrodinâmica Costeira"),
    LABORATORIO_DE_APOIO_MULTIUSUARIO("Laboratorio de Apoio Multiusuario"),

    // Departamento de Geologia
    LABORATORIO_DE_SISMOESTRATIGRAFIA("Laboratorio de Sismoestratigrafia"),
    LABORATORIO_DE_CATODOLUMINESCENCIA("Laboratorio de Catodoluminescencia"),
    LGA("Laboratorio de Geofisica Aplicada (LGA)"),
    LABORATORIO_DE_GEOFISICA_PROF_HELMO_HAND("Laboratorio de Geogisica Prof.º Helmo Hand"),
    GGM("Laboratorio de Geologia e Geofisica Marinha (GGM)"),
    LEGESE("Laboratorio de Geologia Sedimentar e Ambiental (LEGESE)"),
    LABORATORIO_DE_GEOQUIMICA("Laboratorio de Geoquimica"),
    LABHID("Laboratorio de Hodrogeologia (LABHID)"),
    LABORATORIO_DO_ICP("Laboratorio do ICP"),
    LABORATORIO_DE_INCLUSOES_FLUIDAS("Laboratorio de Inclusões Fluidas"),
    LAFIR("Laboratorio de indices Fisicos de Rochas (LAFIR)"),
    LABORATORIO_DE_MICROSCOPIA_OPTICA("Laboratorio de Microscopia optica"),
    MEV_WSD("Lab. de Microscopia  Eletrônica de Varredura (MEV-WSD)"),
    LABORATORIO_DE_PALEONTOLOGIA_DO_DGEO("Laboratorio de Paleontologia do DGEO"),
    LABORATORIO_DE_PREPARACAO_DE_AMOSTRAS_E_LAMINACAO("Laboratorio de Preparacao de Amostras e Laminacao"),
    LABORATORIO_DE_ANALISES_SEDIMENTOLOGICAS("Laboratorio de Analises Sedimentologicas"),
    NEG_LABSE("Nucleo de Estudos Geoquimicos- Laboratorio de Isotopos Estaveis (NEG-LABISE)"),


    // Departamento de Física
    ATOMOS_FRIOS("atomos Frios"),
    DINAMICA_LASER("Dinâmica Laser"),
    ESPALHAMENTO_DE_LUZ_BRILLOUIN("Espalhamento de Luz Brillouin"),
    ESPECTROSCOPIA_ATOMICA_LASER_PULSADO("Espectroscopia Atômica / Laser Pulsado"),
    OTICA_E_FISICA_ATOMICA("otica e Fisica Atômica"),
    FENOMENOS_ULTRA_RAPIDOS_1("Fenômenos Ultra-Rapidos 1"),
    FOTONICA_E_BIOFOTONICA("Fotônica e Biofotônica"),
    IMAGEAMENTO_POR_RESSONANCIA_MAGNETICA_NUCLEAR("Imageamento por Ressonância Magnetica Nuclear"),
    MAGNETOMETRIA("Magnetometria"),
    MAGNETOMETRIA_CAMPOS_INTENSO("Magnetometria - Campos Intenso"),
    MAGNOMETRIA_POR_SQUID("Magnetometria  Por Squid"),
    MAGNETO_OPTICA("Magneto-optica"),
    MICRO_ELETRONICA("Micro Eletrônica"),
    MICROSCOPIA_ELETRONICA_DE_VARREDURA("Microscopia Eletrônica de Varredura"),
    NANO_OPTICA("Nano optica"),
    OPTICA_NAO_LINEAR_E_OPTO_ELETRONICA("optica Não Linear e Opto Eletrônica"),
    POLIMETOS_NAO_CONVENCIONAIS("Polimeros Não Convencionais"),
    PREPARACAO_DE_MATERIAIAS_MAGNETICOS("Preparacao de Materiais Magneticos"),
    RAIO_X_LAB_MATERIAIS_AVANCADOS("Raio X  (Lab. Materiais Avançados)"),
    SUPERCONDUTIVIDADE_TECNICAS_REED("Supercondutividade- Tecnicas Reed"),
    SUPERCONDUTIVIDADE_PROP_DE_TRANSPORTE("Supercondutividade-Prop. De Transporte"),
    SUPERCONDUTIVIDADE_PROP_MAGNETICAS("Supercondutividade-Prop. Magneticas"),
    SUPERCONDUTIVIDADE_SINTESE_DE_MATERIAIS("Supercondutividade-Sintese de Materiais"),
    TRANSPORTE_E_CALORIMETRIA("Transporte e Calorimetria"),
    ALMOXARIFADO("Almoxarifado"),
    CRIOGENIA("Criogenia"),
    ELETRONICA_OFICINA("Eletrônica (Oficina)"),
    FISICA_MODERNA_LABORATORIO("Fisica Moderna (Laboratorio)"),
    INSTRUMENTACAO_P_O_ENSINO_MEDIO("Instrumentacao p o Ensino Medio"),
    MANUTENCAO_OFICINA("Manutencao (Oficina)"),
    MECANICA_OFICINA("Mecânica (oficina)"),
    OPTICA_MODERNA_LABORATORIO("optica Moderna (Laboratorio)"),
    OTIRCA_OFICINA("otica (Oficina)"),
    PREPARACAO_DE_MATERIAIS("Preparacao de Materiais"),
    PREPARACAO_PARA_O_ENSINO_MEDIO("Preparacao para o Ensino Medio"),
    QUIMICA_LABORATORIO("Quimica (Laboratorio)"),
    SALA_LIMPA("Sala Limpa"),
    SPUTTERING("Sputtering"),
    REDES_QUANTICAS("Redes quânticas"),
    ESTADOS_QUANTICOS_DA_LUZ("Estados quânticos da luz"),
    VSM("VSM"),
    RESSONANANCIA_FERROMAGNETICA("Ressonância Ferromagnetica"),
    NANOFENTOLAB("Nanofentolab"),
    PULSOS_ULTRACURTOS_E_ULTRAVIOLETA_EXTERNO("Pulsos Ultracurtos e Ultravioleta externo"),
    LOGICA_QUANTICA("Logica Quântica"),
    METROLOGICA_OPTICA("Metrologia optica"),
    BIOTERIO("Bioterio"),
    RESSONANCIA_MAGNETICA_NUCLEAR("Ressonância Magnetica Nuclear 1/2"),

    // Departamento de Química Fundamental
    CENTRAL_ANALITICA("Central Analitica"),
    IAAQ("Inst. Aut. p/ Anal. Quim. (IAAQ)"),
    COMPOSTOS_HIBRIDOS_INTERFACES("Compostos Hibridos Interfaces"),
    INSTRUMENTOS_P_ENSINO("Instrumento p/ Ensino"),
    OFICINA_DE_HIALOTECNIA("Oficina de Hialotecnia"),
    ECOLOGIA_QUIMICA("Ecologia Quimica"),
    LABORATORIO_RMN("Laboratorio RMN"),
    LEEMM("LEEMM – Lab. Eletroquimica Edson Mororo Moura"),
    LMS("Metodologia e Sintese (LMS"),
    SINTESE_ORGANICA("Sintese Orgânica"),
    CATALISE_E_ORGANOMETALICOS("Catalise e Organometalicos"),
    ELETROANALITICA("Eletroanalitica"),
    ELETROSSINTESE_ORGANICA("Eletrossintese Orgânica"),
    ORGANICA_AVANCADA("Orgânica Avançada"),
    MATERIAIS_VITRIOS_E_NANODISPOSITIVO_FOTONICO("Materiais Vitrios e Nanodispositivo  Fotônico"),
    PRODUTOS_NATURAIS("Produtos Naturais"),
    LAB_DE_BIOMATERIAIS("Lab. Biomateriais"),
    POLIMEROS("Polimeros"),
    TERRAS_RARAS("Terras Raras"),
    ORGANOMETALICOS("Organometalicos"),
    ARQUITETURA_MOLECULAR("Arquitetura Molecular"),
    LQTC_1("Quimica Computacional 1 – LQTC"),
    LQTC_2("Quimica Computacional 2 – LQTC"),
    QUIMICA_DE_ESTADO_SOLIDO("Quimica de Estado Solido"),
    ESPECTROSCOPIA_BSTR_1("Espectroscopia BSTR 1"),
    ESPECTROSCOPIA_BSTR_2("Espectroscopia BSTR 2"),
    LABORATORIO_DE_ENSINO_1_E_2("Laboratorios de Ensino 1 e 2"),
    LABORATORIO_RMN_400_MHZ_CA("Laboratorio RMN 400 MHZ (CA)"),

    /* CE */
    COLEGIO_DE_APLICACAO("Colegio de Aplicacao"),
    LABORATORIO_DE_INFORMATICA_CE("Laboratorio de Informatica"),
    LABORATORIO_DE_QUIMICA("Laboratorio de Quimica"),
    LABORATORIO_DE_MATEMATICA_FISICA("Laboratorio de Matematica/Fisica"),
    LABORATORIO_DE_BIOLOGIA("Laboratorio de Biologia"),

    /* LABORATORIOS INDEPENDENTES */
    DINE_POSITIVA("DINE Positiva"),
    COLEGIO_DE_GENOMA("Laboratorio de Genoma"),
    NUCLEO_DE_PESQUISA_EM_INOVACAO_TERAPEUTICA("Nucleo de Pesquisa em Inovacao Terapeutica"),

    /* LIKA */
    LABORATORIO_DE_IMUNOLOGIA("Laboratorio de Imunologia"),
    LABORATORIO_DE_PATOLOGIA("Laboratorio de Patologia"),
    LABORATORIO_DE_MICROSPIA_ELETRONICA("Laboratorio de Microspia Eletrônica"),
    LABORATORIO_DE_BIOQUIMICA("Laboratorio de Bioquimica"),
    LABORATORIO_DE_MICOLOGIA("Laboratorio de Micologia"),
    LABORATORIO_DE_BIOLOGIA_MOLECULAR_LIKA("Laboratorio de Biologia Molecular"),
    LABORATORIO_DE_VIROLOGIA("Laboratorio de Virologia"),
    LABORATORIO_DE_BIOTECNOLOGIA_LIKA("Laboratorio de Biotecnologia"),
    BIOTERIO_LIKA("Bioterio"),
    NAI("NAI – Nucleo de Atendimento ao Idoso")

    public String value

    LaboratorioList(String value){
        this.value = value
    }

    String toString() {
        value
    }

    String getKey() {
        name()
    }

}